spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ldgr
spring.datasource.username=ldgr
spring.datasource.password=ldgr

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true